/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    "proof-items": ProofItem;
    credentials: Credential;
    "credential-groups": CredentialGroup;
    media: Media;
    articles: Article;
    "article-categories": ArticleCategory;
    "legal-pages": LegalPage;
    enquiries: Enquiry;
    "enquiry-types": EnquiryType;
    users: User;
    "audit-log": AuditLog;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    "proof-items": ProofItemsSelect<false> | ProofItemsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    "credential-groups": CredentialGroupsSelect<false> | CredentialGroupsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    "article-categories": ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    "legal-pages": LegalPagesSelect<false> | LegalPagesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    "enquiry-types": EnquiryTypesSelect<false> | EnquiryTypesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "audit-log": AuditLogSelect<false> | AuditLogSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    "site-settings": SiteSetting;
    home: Home;
    about: About;
    pages: Page;
    seo: Seo;
  };
  globalsSelect: {
    "site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each service page follows the same nine-part layout. The layout is fixed; everything written here is editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Web address of the service page, after /services/. Lowercase letters, numbers and hyphens. Cannot be changed after the first publish.
   */
  slug: string;
  /**
   * Full name of the service.
   */
  title: string;
  /**
   * Used in the footer, tables and the “View …” links.
   */
  shortTitle: string;
  /**
   * One or two sentences shown in service lists.
   */
  summary: string;
  /**
   * What the client gains.
   */
  outcome: string;
  /**
   * Line icon shown beside the service title (FR-45). A fixed set; no shields, padlocks or globes.
   */
  icon:
    | "Cpu"
    | "Network"
    | "Split"
    | "Gauge"
    | "Activity"
    | "Cable"
    | "Server"
    | "Workflow"
    | "Waypoints"
    | "Router"
    | "Cog"
    | "Wrench";
  challenge: string;
  whyItMatters: string;
  capability: string;
  /**
   * Each row is one area of scope with the outputs it produces.
   */
  scopeAndOutputs?:
    | {
        scope: string;
        /**
         * Deliverables for this scope.
         */
        outputs?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Exactly four steps: the page's process animation shows four (D-10).
   */
  deliveryApproach?:
    | {
        /**
         * For example 01.
         */
        step: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Standards references, the most important first.
   */
  standards?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Never name a client, site, plant or network (CLAUDE.md §6). Leave empty to show the placeholder.
   */
  evidence?: string | null;
  relatedServices?: (number | Service)[] | null;
  media: {
    /**
     * Wide image under the page header. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    hero: number | Media;
    /**
     * Shown beside part 3.0 Capability. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    detail: number | Media;
  };
  /**
   * How this page appears in search results. The web address is generated from the page, not typed here.
   */
  seo: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
  };
  /**
   * Off: the service disappears from the site, menus, related links and the sitemap.
   */
  enabled?: boolean | null;
  /**
   * Lower numbers appear first. Items with the same number are sorted by title.
   */
  sortOrder: number;
  /**
   * Set automatically on first publish.
   */
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Images with their rights records. An image appears on the live site only once an approver marks it approved for public use. Never upload photographs that show a client site, plant, equipment tags or screens.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Set by the import. Pages refer to images by this id.
   */
  legacyId?: string | null;
  kind: "image" | "slot";
  assetClass: "photograph" | "illustration" | "issuer-badge";
  /**
   * Describe what the image shows for people who cannot see it. Required unless decorative.
   */
  alt?: string | null;
  /**
   * Tick only if the image adds nothing to the text; it is then hidden from screen readers.
   */
  decorative?: boolean | null;
  /**
   * Shown under the image as a numbered figure caption. Doubles as the attribution line.
   */
  caption?: string | null;
  /**
   * What the photograph for this position should show.
   */
  subject?: string | null;
  /**
   * Path of the photography brief under docs/image-prompts/.
   */
  promptRef?: string | null;
  /**
   * Where the image came from.
   */
  source?: string | null;
  licence?: string | null;
  usageRights?: string | null;
  attribution?: string | null;
  /**
   * Rights confirmed and the image is safe to publish. Unapproved images never appear on the live site. Approvers only; every change is logged.
   */
  approvedForPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Short, anonymised project notes for the Home page. Never include a client, site, plant or network name, or anything that identifies a third party's infrastructure.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-items".
 */
export interface ProofItem {
  id: number;
  /**
   * Set by the import.
   */
  legacyId?: string | null;
  /**
   * For example “Mining”.
   */
  sector: string;
  challenge: string;
  outcome: string;
  /**
   * Optional measurable result.
   */
  metric?: string | null;
  /**
   * The client has agreed this may be published. Unapproved notes never appear on the live site. Approvers only; every change is logged.
   */
  disclosureApproved?: boolean | null;
  /**
   * Must be ticked before this note can be published.
   */
  noIdentifyingDetailsConfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Qualifications, registrations, certifications and platforms. Only verified entries appear on the live site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  /**
   * Set by the import. Not shown on the site.
   */
  legacyId?: string | null;
  category: "qualifications" | "registrations" | "certifications" | "platforms";
  title: string;
  /**
   * The body that issued it.
   */
  issuer: string;
  /**
   * Registration or certificate number, so a reader can check it.
   */
  identifier?: string | null;
  /**
   * Year awarded, four digits.
   */
  year?: string | null;
  /**
   * Expiry year, four digits. The site marks it expired after that year.
   */
  expiry?: string | null;
  /**
   * Public page where the credential can be checked (https).
   */
  url?: string | null;
  /**
   * Issuer badge artwork. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
   */
  badge?: (number | null) | Media;
  /**
   * Confirmed against the issuer. Unverified credentials never appear on the live site. Approvers only; every change is logged.
   */
  verified?: boolean | null;
  /**
   * Lower numbers appear first. Items with the same number are sorted by title.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * The four headings of the credentials register. One group per category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credential-groups".
 */
export interface CredentialGroup {
  id: number;
  category: "qualifications" | "registrations" | "certifications" | "platforms";
  /**
   * Heading shown on the credentials page.
   */
  title: string;
  /**
   * Lower numbers appear first. Items with the same number are sorted by title.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Technical notes for the Insights section. Save drafts freely; only published articles appear, and only while Insights is switched on in Site settings. Never name a client, site, plant or network.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Web address of the article, after /insights/. Lowercase letters, numbers and hyphens. Cannot be changed after the first publish.
   */
  slug: string;
  title: string;
  /**
   * One or two sentences for the article list and search results.
   */
  summary: string;
  /**
   * Headings (H2, H3), bold, italic, links, lists and quotations only.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories?: (number | ArticleCategory)[] | null;
  /**
   * Set on the first publish.
   */
  publishedAt?: string | null;
  /**
   * Worked out from the length.
   */
  readingMinutes?: number | null;
  /**
   * How this page appears in search results. The web address is generated from the page, not typed here.
   */
  seo: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
  };
  /**
   * Set automatically on first publish.
   */
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Categories shown on articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  name: string;
  /**
   * Short identifier for the category. Lowercase letters, numbers and hyphens. Cannot be changed after the first publish.
   */
  slug: string;
  /**
   * Set automatically on first publish.
   */
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Privacy notice, terms of use and accessibility statement. Wording must come from the client's adviser; do not edit it yourself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  /**
   * Which page this is. The web address is fixed.
   */
  slug: "privacy" | "terms" | "accessibility";
  title: string;
  /**
   * As shown on the page, for example “September 2026”.
   */
  lastUpdated: string;
  /**
   * Shown in the document details, for example “Privacy Act 1988 (Cth), APPs”.
   */
  reference: string;
  /**
   * Approvers only; every change is logged. Set to approved only when the adviser has approved the wording.
   */
  status: "pending-adviser" | "approved";
  sections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Every enquiry sent through the contact form. Search by name, email or keyword. Delete an enquiry when it is no longer needed or when the sender asks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  submittedAt: string;
  /**
   * Tick once you have dealt with it.
   */
  read?: boolean | null;
  name: string;
  workEmail: string;
  organisation?: string | null;
  phone?: string | null;
  enquiryTypeValue: string;
  /**
   * As the form showed it, so it stays readable if the type is later changed.
   */
  enquiryTypeLabel: string;
  message: string;
  consent: boolean;
  emailStatus: "pending" | "sent" | "failed" | "simulated";
  /**
   * Short reason only.
   */
  emailError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Options in the contact form's “Area of enquiry” list. Switch one off rather than deleting it; old enquiries keep their own copy of the label.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-types".
 */
export interface EnquiryType {
  id: number;
  /**
   * Stored with each enquiry. Cannot be changed after the type is created.
   */
  value: string;
  /**
   * What the visitor sees.
   */
  label: string;
  /**
   * Off: removed from the form and refused by the server.
   */
  enabled?: boolean | null;
  /**
   * Lower numbers appear first. Items with the same number are sorted by title.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to the CMS. Accounts are created by the developer, not here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the audit log next to this account's changes.
   */
  name?: string | null;
  /**
   * Editors change content. Approvers can also set the approval flags (verified, disclosure approved, approved for public).
   */
  roles: ("editor" | "approver")[];
  totpSecret?: string | null;
  pendingTotpSecret?: string | null;
  totpLastStep?: number | null;
  recoveryCodeHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mfaEnrolledAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * Every sign-in, publish, deletion and approval change. Entries cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  at: string;
  userId?: string | null;
  userEmail?: string | null;
  action:
    | "create"
    | "update"
    | "delete"
    | "publish"
    | "unpublish"
    | "login"
    | "login-blocked"
    | "mfa-enrolled"
    | "mfa-verified"
    | "mfa-failed"
    | "recovery-code-used"
    | "flag-change";
  targetCollection?: string | null;
  docId?: string | null;
  field?: string | null;
  from?: string | null;
  to?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "services";
        value: number | Service;
      } | null)
    | ({
        relationTo: "proof-items";
        value: number | ProofItem;
      } | null)
    | ({
        relationTo: "credentials";
        value: number | Credential;
      } | null)
    | ({
        relationTo: "credential-groups";
        value: number | CredentialGroup;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "articles";
        value: number | Article;
      } | null)
    | ({
        relationTo: "article-categories";
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: "legal-pages";
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: "enquiries";
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: "enquiry-types";
        value: number | EnquiryType;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "audit-log";
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  shortTitle?: T;
  summary?: T;
  outcome?: T;
  icon?: T;
  challenge?: T;
  whyItMatters?: T;
  capability?: T;
  scopeAndOutputs?:
    | T
    | {
        scope?: T;
        outputs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  deliveryApproach?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        value?: T;
        id?: T;
      };
  evidence?: T;
  relatedServices?: T;
  media?:
    | T
    | {
        hero?: T;
        detail?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  enabled?: T;
  sortOrder?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-items_select".
 */
export interface ProofItemsSelect<T extends boolean = true> {
  legacyId?: T;
  sector?: T;
  challenge?: T;
  outcome?: T;
  metric?: T;
  disclosureApproved?: T;
  noIdentifyingDetailsConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  legacyId?: T;
  category?: T;
  title?: T;
  issuer?: T;
  identifier?: T;
  year?: T;
  expiry?: T;
  url?: T;
  badge?: T;
  verified?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credential-groups_select".
 */
export interface CredentialGroupsSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyId?: T;
  kind?: T;
  assetClass?: T;
  alt?: T;
  decorative?: T;
  caption?: T;
  subject?: T;
  promptRef?: T;
  source?: T;
  licence?: T;
  usageRights?: T;
  attribution?: T;
  approvedForPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  summary?: T;
  body?: T;
  categories?: T;
  publishedAt?: T;
  readingMinutes?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  lastUpdated?: T;
  reference?: T;
  status?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  submittedAt?: T;
  read?: T;
  name?: T;
  workEmail?: T;
  organisation?: T;
  phone?: T;
  enquiryTypeValue?: T;
  enquiryTypeLabel?: T;
  message?: T;
  consent?: T;
  emailStatus?: T;
  emailError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-types_select".
 */
export interface EnquiryTypesSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  enabled?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  totpSecret?: T;
  pendingTotpSecret?: T;
  totpLastStep?: T;
  recoveryCodeHashes?: T;
  mfaEnrolledAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  at?: T;
  userId?: T;
  userEmail?: T;
  action?: T;
  targetCollection?: T;
  docId?: T;
  field?: T;
  from?: T;
  to?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company and contact details, labels and switches used on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * As registered, for the footer and copyright line.
   */
  legalName: string;
  /**
   * Short name used in emails and headings.
   */
  displayName: string;
  tagline: string;
  abn?: string | null;
  /**
   * Not shown on the site.
   */
  address?: string | null;
  phone: string;
  email: string;
  /**
   * Profile or company page (https).
   */
  linkedIn?: string | null;
  /**
   * Further profiles. Not shown on the site yet (FR-41).
   */
  socialLinks?:
    | {
        platform: "linkedin" | "x" | "youtube" | "github" | "facebook" | "instagram";
        /**
         * https only.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown wherever the site gives its location.
   */
  locationLabel: string;
  /**
   * A plain “Open in Google Maps” link on the contact page (no embedded map). google.com/maps, maps.google.com, maps.app.goo.gl or goo.gl/maps only.
   */
  mapsUrl?: string | null;
  responseTime: string;
  serviceArea: string;
  officeAddress?: {
    street?: string | null;
    locality?: string | null;
    region?: string | null;
    postcode?: string | null;
  };
  showOfficeAddress?: boolean | null;
  businessHours?:
    | {
        day: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /**
         * 24-hour time, for example 08:30.
         */
        opens?: string | null;
        closes?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  showBusinessHours?: boolean | null;
  /**
   * The pages and their order are fixed; only the wording changes.
   */
  navLabels: {
    home: string;
    about: string;
    services: string;
    credentials: string;
    insights: string;
    contact: string;
  };
  ctaLabels: {
    /**
     * Main button, leads to the contact page.
     */
    primary: string;
    /**
     * Leads to the services page.
     */
    secondary: string;
    credentials: string;
    header: string;
  };
  uiLabels: {
    allServices: string;
    viewService: string;
    /**
     * For example “View”.
     */
    viewPrefix: string;
    returnHome: string;
    connectOnLinkedIn: string;
    /**
     * For example “on LinkedIn”.
     */
    onLinkedInSuffix: string;
    /**
     * For example “Or email”.
     */
    orEmail: string;
    /**
     * For example “or call”.
     */
    orCall: string;
    openInMaps: string;
  };
  /**
   * Shows the Insights section and its menu link. Approvers only; every change is logged.
   */
  insightsEnabled?: boolean | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Text for the nine Home sections. Their order is fixed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    headline: string;
    supportingText: string;
    facts?:
      | {
          label: string;
          value: string;
          mono?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Credentials shown under the hero, in this order. Only verified ones appear on the live site.
   */
  trustStrip?: (number | Credential)[] | null;
  trustStripCopy: {
    title: string;
    registerLinkLabel: string;
    categoryLabels: {
      qualifications: string;
      registrations: string;
      certifications: string;
      platforms: string;
    };
  };
  coreCapabilitiesTitle: string;
  coreCapabilitiesIntro: string;
  /**
   * Optional shorter title and outcome for a service on Home.
   */
  coreCapabilities?:
    | {
        service: number | Service;
        title: string;
        outcome: string;
        id?: string | null;
      }[]
    | null;
  whyDeepTsight: {
    title: string;
    convergenceLabel: string;
    /**
     * One paragraph per row.
     */
    paragraphs?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    pillars?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  problemsAddressed: {
    title: string;
    items?:
      | {
          challenge: string;
          solution: string;
          id?: string | null;
        }[]
      | null;
  };
  deliveryApproach: {
    title: string;
    intro: string;
    steps?:
      | {
          step: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  selectedProofTitle: string;
  /**
   * Project notes shown on Home. Only disclosure-approved notes appear on the live site.
   */
  selectedProof?: (number | ProofItem)[] | null;
  perthContext: {
    title: string;
    description: string;
    officeArea: string;
    /**
     * One sector per row.
     */
    sectors?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The button wording comes from Site settings → Call-to-action labels.
   */
  finalCta: {
    title: string;
    supportingText: string;
  };
  media: {
    /**
     * Beside the problems section. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    problems: number | Media;
    /**
     * Beside the why section. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    why: number | Media;
    /**
     * Wide image above the closing call to action. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    close: number | Media;
  };
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Founder, narrative, principles and career record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Also used in the search-engine description of the founder.
   */
  founder: {
    name: string;
    jobTitle: string;
  };
  narrative: {
    title: string;
    /**
     * The first paragraph is the page introduction.
     */
    paragraphs?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  principles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Never name a client site or plant (CLAUDE.md §6).
   */
  timeline?:
    | {
        period: string;
        role: string;
        context: string;
        id?: string | null;
      }[]
    | null;
  media: {
    /**
     * Founder portrait. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    portrait: number | Media;
    /**
     * Lower image, left. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    site: number | Media;
    /**
     * Lower image, right. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    desk: number | Media;
  };
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Introductions and closing text for Services, Credentials, Contact, thank-you and the service template.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  about: {
    /**
     * The button wording comes from Site settings → Call-to-action labels.
     */
    finalCta: {
      title: string;
      supportingText: string;
    };
  };
  services: {
    title: string;
    lead: string;
    /**
     * The button wording comes from Site settings → Call-to-action labels.
     */
    finalCta: {
      title: string;
      supportingText: string;
    };
    /**
     * Wide image under the page header. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    figure: number | Media;
  };
  serviceTemplate: {
    /**
     * Value of the “Engagement” row.
     */
    engagement: string;
    /**
     * The service name follows it.
     */
    enquiryTitlePrefix: string;
    supportingText: string;
  };
  credentials: {
    title: string;
    lead: string;
    /**
     * The button wording comes from Site settings → Call-to-action labels.
     */
    finalCta: {
      title: string;
      supportingText: string;
    };
    /**
     * Image under the page header. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    figure: number | Media;
  };
  contact: {
    lead: string;
    beforeYouWrite: {
      title: string;
      body: string;
    };
    /**
     * Image beside the form on wide screens. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    figure: number | Media;
  };
  thankYou: {
    title: string;
    lead: string;
    nextStepsTitle: string;
    nextSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Title and description in search results for each fixed page. Service pages have their own on each service. Web addresses are generated, not typed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  home: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  about: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  services: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  credentials: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  insights: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  contact: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  thankYou: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  privacy: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  terms: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  accessibility: {
    /**
     * Aim for 60 characters or fewer. The site name is added automatically.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer.
     */
    description: string;
    /**
     * Optional image for social sharing. Never upload photographs that show a client site, plant, equipment tags or screens (CLAUDE.md §6).
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  displayName?: T;
  tagline?: T;
  abn?: T;
  address?: T;
  phone?: T;
  email?: T;
  linkedIn?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  locationLabel?: T;
  mapsUrl?: T;
  responseTime?: T;
  serviceArea?: T;
  officeAddress?:
    | T
    | {
        street?: T;
        locality?: T;
        region?: T;
        postcode?: T;
      };
  showOfficeAddress?: T;
  businessHours?:
    | T
    | {
        day?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  showBusinessHours?: T;
  navLabels?:
    | T
    | {
        home?: T;
        about?: T;
        services?: T;
        credentials?: T;
        insights?: T;
        contact?: T;
      };
  ctaLabels?:
    | T
    | {
        primary?: T;
        secondary?: T;
        credentials?: T;
        header?: T;
      };
  uiLabels?:
    | T
    | {
        allServices?: T;
        viewService?: T;
        viewPrefix?: T;
        returnHome?: T;
        connectOnLinkedIn?: T;
        onLinkedInSuffix?: T;
        orEmail?: T;
        orCall?: T;
        openInMaps?: T;
      };
  insightsEnabled?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        supportingText?: T;
        facts?:
          | T
          | {
              label?: T;
              value?: T;
              mono?: T;
              id?: T;
            };
      };
  trustStrip?: T;
  trustStripCopy?:
    | T
    | {
        title?: T;
        registerLinkLabel?: T;
        categoryLabels?:
          | T
          | {
              qualifications?: T;
              registrations?: T;
              certifications?: T;
              platforms?: T;
            };
      };
  coreCapabilitiesTitle?: T;
  coreCapabilitiesIntro?: T;
  coreCapabilities?:
    | T
    | {
        service?: T;
        title?: T;
        outcome?: T;
        id?: T;
      };
  whyDeepTsight?:
    | T
    | {
        title?: T;
        convergenceLabel?: T;
        paragraphs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  problemsAddressed?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              challenge?: T;
              solution?: T;
              id?: T;
            };
      };
  deliveryApproach?:
    | T
    | {
        title?: T;
        intro?: T;
        steps?:
          | T
          | {
              step?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  selectedProofTitle?: T;
  selectedProof?: T;
  perthContext?:
    | T
    | {
        title?: T;
        description?: T;
        officeArea?: T;
        sectors?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        title?: T;
        supportingText?: T;
      };
  media?:
    | T
    | {
        problems?: T;
        why?: T;
        close?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  founder?:
    | T
    | {
        name?: T;
        jobTitle?: T;
      };
  narrative?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  principles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        period?: T;
        role?: T;
        context?: T;
        id?: T;
      };
  media?:
    | T
    | {
        portrait?: T;
        site?: T;
        desk?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  about?:
    | T
    | {
        finalCta?:
          | T
          | {
              title?: T;
              supportingText?: T;
            };
      };
  services?:
    | T
    | {
        title?: T;
        lead?: T;
        finalCta?:
          | T
          | {
              title?: T;
              supportingText?: T;
            };
        figure?: T;
      };
  serviceTemplate?:
    | T
    | {
        engagement?: T;
        enquiryTitlePrefix?: T;
        supportingText?: T;
      };
  credentials?:
    | T
    | {
        title?: T;
        lead?: T;
        finalCta?:
          | T
          | {
              title?: T;
              supportingText?: T;
            };
        figure?: T;
      };
  contact?:
    | T
    | {
        lead?: T;
        beforeYouWrite?:
          | T
          | {
              title?: T;
              body?: T;
            };
        figure?: T;
      };
  thankYou?:
    | T
    | {
        title?: T;
        lead?: T;
        nextStepsTitle?: T;
        nextSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  credentials?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  insights?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  thankYou?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  terms?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  accessibility?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
