// Generated by scripts/generate-tokens.ts from src/styles/globals.css. Do not edit.
// Change a colour in globals.css and rebuild; this file follows.

export const colorTokens = {
  ground: "#F2F2F2",
  groundDeep: "#DFE2DF",
  panel: "#F6F7F6",
  white: "#FFFFFF",
  ink900: "#1B2124",
  ink800: "#262E32",
  ink700: "#3A4448",
  steel600: "#555F63",
  control: "#737C80",
  rule: "#C9CECB",
  ruleDark: "#3D474B",
  primary: "#0E50ED",
  primaryDeep: "#0A3FC2",
  primaryOnDark: "#7AA2FF",
  onPrimary: "#FFFFFF",
  onDark: "#E6E9E8",
  onDarkMuted: "#A3ADB1",
  error: "#A4271B",
  status: "#2F6B3A",
} as const;

export type ColorToken = keyof typeof colorTokens;

/** Type-scale names, so cn() knows text-h2 etc. are sizes, not colours. */
export const fontSizeTokens = ["display", "h1", "h2", "h3-lg", "h3", "menu", "wordmark", "lead", "body", "small", "field", "caption", "inline-mono"] as const;
