// Generated by scripts/generate-dither.ts. Do not edit.

/** Perth on public/dither/globe-perth.svg, as fractions of the figure's width and height. */
export const GLOBE_PERTH = { x: 0.4414, y: 0.5608 } as const;
