/**
 * generate-globe-data.ts
 * Precomputes world land points from Natural Earth 110m GeoJSON for the client-side
 * revolving dot-matrix globe.
 *
 * Runs offline at build time; the client loads only the compact pre-computed points.
 * Run with: npx tsx scripts/generate-globe-data.ts
 */
import fs from "node:fs";
import path from "node:path";

type Ring = [number, number][];

function inRing(lon: number, lat: number, ring: Ring): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]!;
    const [xj, yj] = ring[j]!;
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

function inPolygon(lon: number, lat: number, poly: Ring[]): boolean {
  if (!poly[0] || !inRing(lon, lat, poly[0])) return false;
  for (let i = 1; i < poly.length; i++) {
    if (inRing(lon, lat, poly[i]!)) return false;
  }
  return true;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function inGeometry(lon: number, lat: number, geom: any): boolean {
  if (geom.type === "Polygon") return inPolygon(lon, lat, geom.coordinates);
  if (geom.type === "MultiPolygon")
    return geom.coordinates.some((p: Ring[]) => inPolygon(lon, lat, p));
  return false;
}

async function main() {
  console.log("Fetching Natural Earth 110m land polygons...");
  const res = await fetch(
    "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json",
  );
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const geojson = (await res.json()) as any;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const isLand = (lon: number, lat: number) =>
    geojson.features.some((f: any) => inGeometry(lon, lat, f.geometry));

  const isAus = (lon: number, lat: number) =>
    lat >= -44 && lat <= -10 && lon >= 113 && lon <= 154 && isLand(lon, lat);

  const N = 36000;
  const points: [number, number, number][] = [];

  for (let i = 0; i < N; i++) {
    const phi = Math.acos(1 - (2 * (i + 0.5)) / N);
    const theta = Math.PI * (1 + Math.sqrt(5)) * i;
    const lat = +(90 - (phi * 180) / Math.PI).toFixed(2);
    const lon = +((((((theta * 180) / Math.PI) % 360) + 360) % 360) - 180).toFixed(2);

    if (isLand(lon, lat)) {
      // 2 = Australia (accent tone), 1 = Other land
      const type = isAus(lon, lat) ? 2 : 1;
      points.push([lat, lon, type]);
    }
  }

  const outPath = path.resolve("src/components/content/globe-data.generated.ts");
  const content =
    `// Generated by scripts/generate-globe-data.ts. Do not edit directly.\n\n` +
    `/** [lat, lon, type] where type 2 = Australia (primary accent), 1 = other land */\n` +
    `export const GLOBE_LAND_POINTS: readonly [number, number, number][] = ${JSON.stringify(points)} as const;\n\n` +
    `export const PERTH_COORDS = { lat: -31.95, lon: 115.86 } as const;\n`;

  fs.writeFileSync(outPath, content, "utf-8");
  console.log(`Wrote ${points.length} land points to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
