/**
 * generate-tokens.ts
 * Writes src/styles/tokens.generated.ts from the colour tokens in globals.css, for the places
 * CSS variables cannot reach: the enquiry email (inline styles for mail clients) and the social
 * share image (rendered by next/og). Runs before every build via check:content.
 */
import fs from "node:fs";
import path from "node:path";
import { readColorTokens, readFontSizeTokens } from "./lib/read-design-tokens";

const OUT = path.resolve("src/styles/tokens.generated.ts");

const tokens = readColorTokens();
const fontSizes = readFontSizeTokens();
const toKey = (name: string) => name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const body = Object.entries(tokens)
  .map(([name, value]) => `  ${toKey(name)}: "${value}",`)
  .join("\n");

const file = `// Generated by scripts/generate-tokens.ts from src/styles/globals.css. Do not edit.
// Change a colour in globals.css and rebuild; this file follows.

export const colorTokens = {
${body}
} as const;

export type ColorToken = keyof typeof colorTokens;

/** Type-scale names, so cn() knows text-h2 etc. are sizes, not colours. */
export const fontSizeTokens = [${fontSizes.map((n) => `"${n}"`).join(", ")}] as const;
`;

const previous = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf-8") : "";
if (previous !== file) {
  fs.writeFileSync(OUT, file);
  console.log(
    `Updated ${path.relative(process.cwd(), OUT)} with ${Object.keys(tokens).length} colours.`,
  );
} else {
  console.log("Colour tokens up to date.");
}
